import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import React from "react";
import { StoreProvider } from "@/lib/provider/storeProvider";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <StoreProvider>
      <html lang={params.locale}>
        <body className={`${poppins.className} overflow-x-hidden`}>
          <Navbar />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
